dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
networks:
  development:
    verify: False
  ganache:
    verify: False  
  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C' #kovan.etherscan.io'dan alınacak
    fau_token: '0xFab46E002BbF0b4509813474841E0716E6730136' #erc20faucet.com'dan alınan tokenlar
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    dai_usd_price_feed: "0x777A68032a88E5A84678A77Af2CD65A7b3c0775a" #docs.chain.link/docs/ethereum-addresses/ -> eth data feeds -> kovan -> dai/usd
    verify: True
    #dai_usd_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4' #docs.chain.link/docs/ethereum-addresses/ -> eth data feeds -> kovan -> dai/usd
